[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/about"
  to = "https://about.kinopio.club"
  status = 301

[[redirects]]
  from = "/api"
  to = "https://about.kinopio.club/api"
  status = 301

[[redirects]]
  from = "/forum"
  to = "https://forum.kinopio.club"
  status = 301

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/h2sR45Nby8"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
